---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: jenkins-prod
spec:
  selector:
    tier: jenkins-prod
    io.kompose.service: jenkins-prod
  ports:
    - port: 8080
      targetPort:  8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Forwarded-For $proxy_add_x_forwarded_for";
      more_set_headers "X-Forwarded-Proto $scheme";
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: jenkins-prod
                port:
                  number: 8080

