apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: juicy-shop-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /owasp(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-juice-shop
                port:
                  number: 3000
